
name: Generate updated files with SHA256 checksums

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x
          
      - name: Prepare environment
        run: |
          mkdir -p /home/runner/working/bin
          git clone https://github.com/GrapheneOS/adevtool /home/runner/working/adevtool
          curl https://raw.githubusercontent.com/maade69/adevtool/13/scripts/append-sha256.py --output /home/runner/working/adevtool/scripts/append-sha256.py
          curl https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/7.3.1-8691043/aapt2-7.3.1-8691043-linux.jar --output /home/runner/working/bin/aapt2.jar
          unzip /home/runner/working/bin/aapt2.jar -d /home/runner/working/bin/
      
      - name: Run the script
        run: bash run.sh

             
 
